# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "action-guard"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Westgeest"]
  s.date = "2012-06-06"
  s.description = "authorisation module of actions based on url-paths for usage in Rails and possibly other ruby based web frameworks"
  s.email = "rob.westgeest@qwan.it"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".gitignore",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "action-guard.gemspec",
    "lib/action-guard.rb",
    "lib/action-guard/base.rb",
    "lib/action-guard/role.rb",
    "lib/action-guard/rules.rb",
    "lib/action-guard/syntax.rb",
    "lib/action-guard/version.rb",
    "script/authorization.rules",
    "script/console",
    "spec/action-guard_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/rwestgeest/action-guard"
  s.licenses = ["MIT"]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Action guard-1.1.0"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ZenTest>, [">= 4.2.0"])
      s.add_development_dependency(%q<rspec>, ["> 2.5.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ZenTest>, [">= 4.2.0"])
      s.add_dependency(%q<rspec>, ["> 2.5.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ZenTest>, [">= 4.2.0"])
    s.add_dependency(%q<rspec>, ["> 2.5.0"])
  end
end

